import jsPDF from 'jspdf';
import { ContrastReport, ColorPair } from './colorContrast';

export function generatePDFReport(report: ContrastReport): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 212, 255);
  doc.text('Color Contrast Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  
  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`URL: ${report.url}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Generated: ${report.timestamp}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Total Pairs: ${report.totalPairs} | Passed: ${report.passed} | Failed: ${report.failed}`, 20, yPosition);
  
  yPosition += 15;
  
  // Summary box
  doc.setDrawColor(0, 212, 255);
  doc.setLineWidth(0.5);
  doc.rect(20, yPosition, pageWidth - 40, 30);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 25, yPosition + 10);
  
  const passRate = ((report.passed / report.totalPairs) * 100).toFixed(1);
  doc.setFontSize(10);
  doc.text(`Pass Rate: ${passRate}%`, 25, yPosition + 20);
  doc.text(`WCAG AA Compliance: ${report.passed}/${report.totalPairs}`, 25, yPosition + 27);
  
  yPosition += 45;
  
  // Color pairs
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Color Pair Details', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(9);
  
  report.colorPairs.forEach((pair: ColorPair, index: number) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Color boxes
    const boxSize = 10;
    const fgColor = hexToRGB(pair.foreground);
    const bgColor = hexToRGB(pair.background);
    
    if (fgColor && bgColor) {
      doc.setFillColor(fgColor.r, fgColor.g, fgColor.b);
      doc.rect(20, yPosition, boxSize, boxSize, 'F');
      
      doc.setFillColor(bgColor.r, bgColor.g, bgColor.b);
      doc.rect(32, yPosition, boxSize, boxSize, 'F');
    }
    
    // Details
    doc.setTextColor(0, 0, 0);
    doc.text(`${pair.foreground} / ${pair.background}`, 45, yPosition + 7);
    
    const status = pair.wcagAA ? '✓ PASS' : '✗ FAIL';
    const statusColor = pair.wcagAA ? [0, 255, 136] : [255, 46, 151];
    doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.text(status, pageWidth - 60, yPosition + 7);
    
    doc.setTextColor(100, 100, 100);
    doc.text(`Ratio: ${pair.contrastRatio.toFixed(2)}:1`, pageWidth - 40, yPosition + 7);
    
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(8);
    doc.text(pair.selector, 45, yPosition + 12);
    
    doc.setFontSize(9);
    yPosition += 20;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Contrast Analyzer | WCAG 2.1 Guidelines', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  // Save
  doc.save(`contrast-report-${Date.now()}.pdf`);
}

function hexToRGB(hex: string): { r: number; g: number; b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : null;
}

export function generateJSONReport(report: ContrastReport): void {
  const jsonStr = JSON.stringify(report, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `contrast-report-${Date.now()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
